### ISSUE TITLE
Database migration - TrainSize to TrainCorpusSize

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#15]
Here is the error: 
```
Fri, Jul 22 2022 4:18:22 pm | Connection id "0HMJC3RKQD719", Request id "0HMJC3RKQD719:00000002": An unhandled exception was thrown by the application.
Fri, Jul 22 2022 4:18:22 pm | System.FormatException: Element 'trainSize' does not match any field or property of class SIL.Machine.WebApi.Models.TranslationEngine.
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.Serializers.EnumerableSerializerBase`2.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Operations.AggregateOperation`1.CursorDeserializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Operations.AggregateOperation`1.AggregateResultDeserializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.ExecuteAsync[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Operations.AggregateOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.Core.Operations.AggregateOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.MongoCollectionImpl`1.AggregateAsync[TResult](IClientSessionHandle session, PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
Fri, Jul 22 2022 4:18:22 pm | at SIL.Machine.WebApi.DataAccess.MongoRepository`1.GetAllAsync(Expression`1 filter, CancellationToken cancellationToken) in /app/src/SIL.Machine.WebApi/DataAccess/MongoRepository.cs:line 59
Fri, Jul 22 2022 4:18:22 pm | at SIL.Machine.WebApi.Services.TranslationEngineService.GetAllAsync(String owner) in /app/src/SIL.Machine.WebApi/Services/TranslationEngineService.cs:line 94
Fri, Jul 22 2022 4:18:22 pm | at SIL.Machine.WebApi.Controllers.TranslationEnginesController.GetAllAsync() in /app/src/SIL.Machine.WebApi/Controllers/TranslationEnginesController.cs:line 40
Fri, Jul 22 2022 4:18:22 pm | at lambda_method612(Closure , Object )
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited\|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Fri, Jul 22 2022 4:18:22 pm | at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
Fri, Jul 22 2022 4:18:22 pm | at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
Fri, Jul 22 2022 4:18:22 pm | at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
Fri, Jul 22 2022 4:18:22 pm | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext]
```
This was caused when TrainSize changed to TrainCorpusSize.  This will crash the server when reading old data.  We should be able to deal gracefully with old data - and give more intelligent errors than HTTP 500 - Strict-Transport-Security.

**Comment by johnml1135** [comment]
We are making the plan to "just be more careful" with adding new fields.  This should not happen again.  The error was able to be debugged by looking at the k8s log.  This is acceptable right now.
