### ISSUE TITLE
Fix USFM parsing issues

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/machine#228]
After running the [manual tests on all SF projects](https://github.com/sillsdev/serval/issues/429), here are the 5 that failed, @ddaspit, @johnml1135:

```

Multiple failures or warnings in test:
  1)   Failed to parse project aSno:
  Expected: No Exception to be thrown
  But was:  <System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at SIL.Machine.Corpora.UsfmTextUpdater.PopNewTokens() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 396
   at SIL.Machine.Corpora.UsfmTextUpdater.EndVerseText(UsfmParserState state, IReadOnlyList`1 scriptureRefs) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 253
   at SIL.Machine.Corpora.ScriptureRefUsfmParserHandlerBase.Verse(UsfmParserState state, String number, String marker, String altNumber, String pubNumber) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs:line 58
   at SIL.Machine.Corpora.UsfmTextUpdater.Verse(UsfmParserState state, String number, String marker, String altNumber, String pubNumber) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 148
   at SIL.Machine.Corpora.UsfmParser.ProcessToken() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 396
   at SIL.Machine.Corpora.UsfmParser.ProcessTokens() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 132
   at SIL.Machine.Corpora.UsfmParser.Parse(String usfm, IUsfmParserHandler handler, UsfmStylesheet stylesheet, ScrVers versification, Boolean preserveWhitespace) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 44
   at SIL.Machine.Corpora.UsfmManualTests.<CreateUsfmFile>g__GetUsfmAsync|4_0(String projectPath) in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 135
   at SIL.Machine.Corpora.UsfmManualTests.<>c__DisplayClass4_1.<<CreateUsfmFile>b__7>d.MoveNext() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.ExceptionHelper.RecordException(Delegate parameterlessDelegate, String parameterName)>

  2)   Failed to parse project RVEES95:
  Expected: No Exception to be thrown
  But was:  <System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SIL.Machine.Corpora.UsfmTextUpdater.ReplaceWithNewTokens(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 368
   at SIL.Machine.Corpora.UsfmTextUpdater.OptBreak(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 226
   at SIL.Machine.Corpora.UsfmParser.ProcessToken() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 559
   at SIL.Machine.Corpora.UsfmParser.ProcessTokens() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 132
   at SIL.Machine.Corpora.UsfmParser.Parse(String usfm, IUsfmParserHandler handler, UsfmStylesheet stylesheet, ScrVers versification, Boolean preserveWhitespace) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 44
   at SIL.Machine.Corpora.UsfmManualTests.<CreateUsfmFile>g__GetUsfmAsync|4_0(String projectPath) in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 135
   at SIL.Machine.Corpora.UsfmManualTests.<>c__DisplayClass4_1.<<CreateUsfmFile>b__7>d.MoveNext() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.ExceptionHelper.RecordException(Delegate parameterlessDelegate, String parameterName)>

  3)   Failed to parse project JraLM:
  Expected: No Exception to be thrown
  But was:  <System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SIL.Machine.Corpora.UsfmTextUpdater.ReplaceWithNewTokens(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 368
   at SIL.Machine.Corpora.UsfmTextUpdater.OptBreak(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 226
   at SIL.Machine.Corpora.UsfmParser.ProcessToken() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 559
   at SIL.Machine.Corpora.UsfmParser.ProcessTokens() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 132
   at SIL.Machine.Corpora.UsfmParser.Parse(String usfm, IUsfmParserHandler handler, UsfmStylesheet stylesheet, ScrVers versification, Boolean preserveWhitespace) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 44
   at SIL.Machine.Corpora.UsfmManualTests.<CreateUsfmFile>g__GetUsfmAsync|4_0(String projectPath) in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 135
   at SIL.Machine.Corpora.UsfmManualTests.<>c__DisplayClass4_1.<<CreateUsfmFile>b__7>d.MoveNext() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.ExceptionHelper.RecordException(Delegate parameterlessDelegate, String parameterName)>

  4)   Failed to parse project ABP:
  Expected: No Exception to be thrown
  But was:  <System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SIL.Machine.Corpora.UsfmTextUpdater.ReplaceWithNewTokens(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 368
   at SIL.Machine.Corpora.UsfmTextUpdater.OptBreak(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 226
   at SIL.Machine.Corpora.UsfmParser.ProcessToken() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 559
   at SIL.Machine.Corpora.UsfmParser.ProcessTokens() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 132
   at SIL.Machine.Corpora.UsfmParser.Parse(String usfm, IUsfmParserHandler handler, UsfmStylesheet stylesheet, ScrVers versification, Boolean preserveWhitespace) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 44
   at SIL.Machine.Corpora.UsfmManualTests.<CreateUsfmFile>g__GetUsfmAsync|4_0(String projectPath) in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 135
   at SIL.Machine.Corpora.UsfmManualTests.<>c__DisplayClass4_1.<<CreateUsfmFile>b__7>d.MoveNext() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.ExceptionHelper.RecordException(Delegate parameterlessDelegate, String parameterName)>

  5)   Failed to parse project SekoP:
  Expected: No Exception to be thrown
  But was:  <System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SIL.Machine.Corpora.UsfmTextUpdater.ReplaceWithNewTokens(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 368
   at SIL.Machine.Corpora.UsfmTextUpdater.OptBreak(UsfmParserState state) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmTextUpdater.cs:line 226
   at SIL.Machine.Corpora.UsfmParser.ProcessToken() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 559
   at SIL.Machine.Corpora.UsfmParser.ProcessTokens() in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 132
   at SIL.Machine.Corpora.UsfmParser.Parse(String usfm, IUsfmParserHandler handler, UsfmStylesheet stylesheet, ScrVers versification, Boolean preserveWhitespace) in /home/enkidu/SILdev/machine/src/SIL.Machine/Corpora/UsfmParser.cs:line 44
   at SIL.Machine.Corpora.UsfmManualTests.<CreateUsfmFile>g__GetUsfmAsync|4_0(String projectPath) in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 135
   at SIL.Machine.Corpora.UsfmManualTests.<>c__DisplayClass4_1.<<CreateUsfmFile>b__7>d.MoveNext() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.ExceptionHelper.RecordException(Delegate parameterlessDelegate, String parameterName)>


   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 142
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

1)    at SIL.Machine.Corpora.UsfmManualTests.<>c.<CreateUsfmFile>b__4_1() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 142
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile()

2)    at SIL.Machine.Corpora.UsfmManualTests.<>c.<CreateUsfmFile>b__4_1() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 142
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile()

3)    at SIL.Machine.Corpora.UsfmManualTests.<>c.<CreateUsfmFile>b__4_1() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 142
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile()

4)    at SIL.Machine.Corpora.UsfmManualTests.<>c.<CreateUsfmFile>b__4_1() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 142
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile()

5)    at SIL.Machine.Corpora.UsfmManualTests.<>c.<CreateUsfmFile>b__4_1() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 145
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile() in /home/enkidu/SILdev/machine/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs:line 142
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SIL.Machine.Corpora.UsfmManualTests.CreateUsfmFile()

```

**Comment by ddaspit** [comment]
@Enkidu93 Where can I access the projects that failed?

**Comment by ddaspit** [comment]
You can go ahead and take this issue. In the past, the underlying USFM parsing issues have not been obvious and the surface-level cause was often a red herring. I just want to be able to verify the core issues against the failing projects.

**Comment by Enkidu93** [comment]
Update:
* I've added a new exception to give us/SF better insight into where the USFM parsing failed (in an upcoming PR)
* The `System.ArgumentOutOfRangeException` are the result of an off-by-one error in the `UsfmTextUpdater` class (also in an upcoming PR)
* I'm currently investigating the stack issue. I'll probably hold out and submit a single PR with all these changes since it's moving along quickly enough.
