### ISSUE TITLE
Another USFM-parsing Stack Empty

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/machine#242]
```
System.InvalidOperationException: An error occurred while parsing the text 'EXO' in project '[See me for project name]'. Verse: EXO 7:0, line: 274, character: 2, error: 'Stack empty.'
       ---> System.InvalidOperationException: Stack empty.
         at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
         at SIL.Machine.Corpora.UsfmTextBase.TextRowCollector.OptBreak(UsfmParserState state)
...
```

@johnml1135, all relevant changes are deployed to QA, correct? (This error was on QA).

**Comment by johnml1135** [comment]
Yes, they are all on QA.

**Comment by ddaspit** [comment]
@Enkidu93 Can you send me the project?
