### ISSUE TITLE
NullReferenceException in Terms Parsing

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/machine#244]
We recently got this error on production:
```
System.NullReferenceException: Object reference not set to an instance of an object.
         at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.GroupedEnumerable`3.GetEnumerator()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at SIL.Machine.Corpora.ParatextProjectTermsParserBase.Parse(IEnumerable`1 termCategories, Boolean useTermGlosses)
```
Unfortunately, we don't have line numbers for the Machine code so it's not clear which `ToDictionary` is causing this. It's possible that it's getting a null gloss value (?).

**Comment by johnml1135** [comment]
I can't find the build on the server, or the database - 66e4aeeae234a38f4faa59b3.

My best guess for a resolution is to have both "SelectsMany" calls above the ToDictionary have a null  coalescing because this is .netstandard2.0 and has no explicit null checking enforcement.

**Comment by johnml1135** [comment]
I can't recreate the error.  I'm passing on this until we get better data.
