### ISSUE TITLE
Delete failing with files in directory

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#58]
```
{"log":"\u001B[41m\u001B[30mfail\u001B[39m\u001B[22m\u001B[49m: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'Delete'.
      System.IO.IOException: Directory not empty : '/var/lib/machine/engines/64e6752b6f044714a98cf08f/tm'
         at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
         at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
         at System.IO.Directory.Delete(String path, Boolean recursive)
         at SIL.Machine.AspNetCore.Services.ThotSmtModelFactory.Cleanup(String engineId) in /app/src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs:line 71
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineState.DeleteDataAsync() in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineState.cs:line 69
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineService.DeleteAsync(String engineId, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs:line 60
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineService.DeleteAsync(String engineId, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs:line 60
         at SIL.Machine.AspNetCore.Services.ServalTranslationEngineServiceV1.Delete(DeleteRequest request, ServerCallContext context) in /app/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs:line 33
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at SIL.Machine.AspNetCore.Services.UnimplementedInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in /app/src/SIL.Machine.AspNetCore/Services/UnimplementedInterceptor.cs:line 21
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall\|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
","stream":"stdout","time":"2023-08-23T22:30:47.507725379Z","type":"fail","source":"Grpc.AspNetCore.Server.ServerCallHandler"}
--
```
Likely a flag is not being passed.  Needs more investigation.

**Comment by johnml1135** [comment]
This proposes a resolution - https://stackoverflow.com/questions/329355/cannot-delete-directory-with-directory-deletepath-true.

Why is this the first time it showed up?  I don't know.  Implementing this fix should work though.
