### ISSUE TITLE
Throw error for unbuilt engine

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#81]
This test fails:
```
  Failed CircuitousRouteGetWordGraphAsync [3 s]
  Error Message:
     Expected: <Serval.Client.ServalApiException>
  But was:  null

  Stack Trace:
     at Serval.E2ETests.ServalApiTests.CircuitousRouteGetWordGraphAsync() in /home/runner/work/serval/serval/tests/Serval.E2ETests/ServalApiTests.cs:line 155
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

1)    at Serval.E2ETests.ServalApiTests.CircuitousRouteGetWordGraphAsync() in /home/runner/work/serval/serval/tests/Serval.E2ETests/ServalApiTests.cs:line 155
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)`
```

We need to return back the proper error code saying in effect "the engine needs to be built first."  This check was in Serval but needs to be moved to machine.

**Comment by Enkidu93** [comment]
Fixed here: https://github.com/sillsdev/machine/pull/82
